// Compatibility entry point; implementation is organized by domain.
export type { AxisStatus } from './requirementVerdicts/types.js';
export type { AxisVerdict } from './requirementVerdicts/types.js';
export type { AxisImpactLevel } from './requirementVerdicts/types.js';
export type { OverallLevel } from './requirementVerdicts/types.js';
export type { OverallVerdict } from './requirementVerdicts/types.js';
export type { RequestedRentRange } from './requirementVerdicts/types.js';
export type { RentSegment } from './requirementVerdicts/types.js';
export type { ListingVerdictStatus } from './requirementVerdicts/types.js';
export type { ListingPriceVerdictContext } from './requirementVerdicts/types.js';
export type { RentalPriceFactor } from './requirementVerdicts/types.js';
export type { ListingPriceVerdict } from './requirementVerdicts/types.js';
export type { SalePriceFactor } from './requirementVerdicts/types.js';
export type { SalePriceInsightPoint } from './requirementVerdicts/types.js';
export type { SalePriceVerdict } from './requirementVerdicts/types.js';
export { axisImpactLevel } from './requirementVerdicts/assessment.js';
export { buildAxisVerdicts } from './requirementVerdicts/assessment.js';
export { buildOverallVerdict } from './requirementVerdicts/assessment.js';
export { hasKnownCommuteStations } from './requirementVerdicts/shared.js';
export { resolveSearchScope } from './requirementVerdicts/rentScope.js';
export { estimateRequestedRent } from './requirementVerdicts/rentScope.js';
export { buildSalePriceVerdict } from './requirementVerdicts/salePrice.js';
export { buildListingPriceVerdict } from './requirementVerdicts/rentalPrice.js';
