import type { CalculatorTabProps } from '../lib/calculator/types';
import type { CalculatorState } from './useCalculatorState';
export type CalculatorFormContext = Pick<CalculatorState,
  "setGuidedDistrictSelections"
  | "setGuidedStationSelections"
  | "setGuidedMinArea"
  | "setGuidedAgeMax"
  | "setGuidedCommuteStation"
  | "setGuidedCommuteMinutes"
  | "setGuidedAutoLock"
  | "setGuidedElevator"
  | "setGuidedStructure"
  | "setGuidedLine"
  | "setGuidedLineSelections"
  | "setRentMonthlyBudgetMin"
  | "setRentMonthlyBudget"
  | "setRentUpfrontCash"
  | "setRentSearchFilters"
  | "setAppliedNotice"
  | "setShowAdvancedTools"
  | "rentSearchFilters"
  | "guidedStructure"
  | "guidedAutoLock"
  | "guidedElevator"
  | "guidedLine"
  | "guidedDistrictSelections"
  | "guidedCommuteStation"
  | "setLocationGuardNotice"
  | "guidedStationSelections"
  | "guidedLineSelections"
  | "guidedStationDraft"
  | "setGuidedStationDraft"
  | "guidedMinArea"
  | "rentMonthlyBudgetMin"
  | "rentMonthlyBudget"
  | "guidedCommuteMinutes"
  | "guidedVisaType"
  | "guidedApplicationChannel"
  | "guidedAgeMax"
  | "setGuidedVisaType"
  | "setGuidedApplicationChannel"> & Pick<CalculatorTabProps,
    "setCalcMode"
    | "setCalcDistrict"
    | "setCalcRoomType"
    | "setCalcStation"
    | "setCalcModifiers"
    | "calcModifiers"
    | "calcBuyModifiers"
    | "setCalcBuyModifiers"
    | "calcRoomType"
    | "calcDistrict">;
