import { buildListingReportModel } from '../lib/listing/reportModel';
import type { ListingHealthCheckProps } from '../lib/listing/types';
import { createListingAnalysisActions } from './createListingAnalysisActions';
import { createListingLocationActions } from './createListingLocationActions';
import { createListingShareActions } from './createListingShareActions';
import { useListingPreview } from './useListingPreview';
import { useListingState } from './useListingState';
import { useSharedListing } from './useSharedListing';

export function useListingHealthCheckController({ sharedId }: ListingHealthCheckProps = {}) {
  const sharedMode = Boolean(sharedId);
  const {
    requests,
    sharedTitle,
    setSharedTitle,
    sharedExpiresAt,
    setSharedExpiresAt,
    file,
    setFile,
    previewUrl,
    setPreviewUrl,
    previewImageUrl,
    setPreviewImageUrl,
    showFullPreview,
    setShowFullPreview,
    previewAspect,
    setPreviewAspect,
    previewState,
    setPreviewState,
    isDragging,
    setIsDragging,
    loading,
    setLoading,
    error,
    setError,
    result,
    setResult,
    analysisMode,
    locationContext,
    setLocationContext,
    locationLoading,
    setLocationLoading,
    locationError,
    setLocationError,
    commuteDestination,
    setCommuteDestination,
    commuteLoading,
    setCommuteLoading,
    commuteError,
    setCommuteError,
    commute,
    setCommute,
    shareTitle,
    setShareTitle,
    shareUrl,
    setShareUrl,
    shareLoading,
    setShareLoading,
    shareError,
    setShareError,
    shareCopied,
    setShareCopied,
    pdfLoading,
    setPdfLoading,
    pdfError,
    setPdfError,
    showInitialCostDetails,
    setShowInitialCostDetails,
    showSaleCostsDetails,
    setShowSaleCostsDetails,
    crimeData,
    setCrimeData,
    prefectureSafety,
    setPrefectureSafety,
    crimeLoading,
    setCrimeLoading,
    inputRef,
  } = useListingState();
  const resetReport = () => {
    requests.invalidate("analysis", "location", "crime", "commute", "share", "pdf", "clipboard");
    setLoading(false);
    setLocationLoading(false);
    setCrimeLoading(false);
    setCommuteLoading(false);
    setShareLoading(false);
    setPdfLoading(false);
    setError(null);
    setResult(null);
    setLocationContext(null);
    setLocationError(null);
    setCrimeData(null);
    setPrefectureSafety(null);
    setCommute(null);
    setCommuteError(null);
    setShareUrl(null);
    setShareError(null);
    setShareCopied(false);
    setPdfError(null);
  };
  const {
    loadLocationContext,
    analyzeCommute,
  } = createListingLocationActions({
    requests,
    setLocationError,
    setLocationLoading,
    setLocationContext,
    setCrimeLoading,
    setPrefectureSafety,
    setCrimeData,
    commuteDestination,
    locationContext,
    result,
    commuteLoading,
    setCommute,
    setCommuteError,
    setCommuteLoading,
  });
  const {
    analyze,
  } = createListingAnalysisActions({
    requests,
    resetReport,
    file,
    loading,
    setLoading,
    setError,
    setResult,
    setLocationContext,
    setLocationError,
    setCommute,
    setCommuteError,
    setCrimeData,
    setPrefectureSafety,
    analysisMode,
    loadLocationContext,
  });
  useSharedListing({ requests, resetReport, sharedId, setLoading, setError, setSharedTitle, setSharedExpiresAt, setResult, loadLocationContext });
  const {
    handleFileSelect,
    handleDragOver,
    handleDragLeave,
    handleDrop,
    removeFile,
  } = useListingPreview({
    requests,
    resetReport,
    showFullPreview,
    setShowFullPreview,
    previewUrl,
    previewImageUrl,
    setError,
    setResult,
    setLocationContext,
    setCommute,
    setCrimeData,
    setPrefectureSafety,
    setFile,
    setPreviewUrl,
    setPreviewImageUrl,
    setPreviewAspect,
    setPreviewState,
    setIsDragging,
  });

  const {
    extracted,
    parsed,
    rent,
    managementFee,
    totalMonthlyCost,
    initialCost,
    initialCostTips,
    parsedArea,
    displayArea,
    displayStructure,
    formattedShikibiki,
    hasPenalty,
    cleanVerdictHeadline,
    cleanVerdictDetail,
    isSaleListing,
    listingAudit,
    saleAnalysis,
    specialSale,
    isSpecialSale,
    specialComparison,
    effectiveMlitComparison,
    taxEstimationSummary,
    acquisitionTaxAssessment,
    saleInitialCosts,
    reportHeading,
    isPdfPreview,
    equipmentList,
    stationItems,
  } = buildListingReportModel(result, file);
  const {
    createShareLink,
    copyShareUrl,
    downloadPdf,
  } = createListingShareActions({
    requests,
    result,
    shareLoading,
    shareTitle,
    setShareError,
    setShareLoading,
    setShareUrl,
    shareUrl,
    setShareCopied,
    pdfLoading,
    setPdfLoading,
    setPdfError,
    sharedMode,
    sharedTitle,
    reportHeading,
    sharedId,
    locationContext,
    commute,
  });

  return {
    sharedMode,
    sharedTitle,
    sharedExpiresAt,
    inputRef,
    handleFileSelect,
    file,
    handleDragOver,
    handleDragLeave,
    handleDrop,
    isDragging,
    previewImageUrl,
    setShowFullPreview,
    previewAspect,
    isPdfPreview,
    previewUrl,
    previewState,
    loading,
    removeFile,
    analyze,
    result,
    error,
    showFullPreview,
    isSaleListing,
    reportHeading,
    listingAudit,
    saleAnalysis,
    effectiveMlitComparison,
    locationContext,
    extracted,
    isSpecialSale,
    specialComparison,
    specialSale,
    parsedArea,
    displayArea,
    displayStructure,
    stationItems,
    equipmentList,
    saleInitialCosts,
    taxEstimationSummary,
    showSaleCostsDetails,
    setShowSaleCostsDetails,
    acquisitionTaxAssessment,
    totalMonthlyCost,
    rent,
    managementFee,
    parsed,
    cleanVerdictDetail,
    cleanVerdictHeadline,
    initialCost,
    showInitialCostDetails,
    setShowInitialCostDetails,
    initialCostTips,
    formattedShikibiki,
    hasPenalty,
    locationLoading,
    locationError,
    loadLocationContext,
    crimeLoading,
    crimeData,
    prefectureSafety,
    commuteDestination,
    setCommuteDestination,
    analyzeCommute,
    commuteLoading,
    commuteError,
    commute,
    shareTitle,
    setShareTitle,
    setShareError,
    shareUrl,
    copyShareUrl,
    shareCopied,
    createShareLink,
    shareLoading,
    downloadPdf,
    pdfLoading,
    shareError,
    pdfError,
  };
}
export type ListingHealthCheckModel = ReturnType<typeof useListingHealthCheckController>;
